### ISSUE TITLE
rest-framework login does not work properly !

### ISSUE THREAD

**Issue by GeorgeOrzanescu** [veryacademy/YT-Django-DRF-Simple-Blog-Series-JWT-Part-3#1]
Hay , I have encountered an issue with the authentication on the Django rest framework. It gives a 401 response. I tried running the code from the repository directly and the issue is still there.  
If u remove from the settings.py the JWTAuthentication class , it works again.

**Comment by A1000carZ** [comment]
> Hay , I have encountered an issue with the authentication on the Django rest framework. It gives a 401 response. I tried running the code from the repository directly and the issue is still there.
> If u remove from the settings.py the JWTAuthentication class , it works again.

Hey here is the answer : https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html#user-authentication-rule

**Comment by GeorgeOrzanescu** [comment]
> > Hay , I have encountered an issue with the authentication on the Django rest framework. It gives a 401 response. I tried running the code from the repository directly and the issue is still there.
> > If u remove from the settings.py the JWTAuthentication class , it works again.
> 
> Hey here is the answer : https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html#user-authentication-rule

I know now that it's not an issue. The link u provided does not explain much related on how the two authentication system interact. Anyway thanks.
